//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Walterlv.Miracle.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://cn.bing.com/")]
        public string BingUrl {
            get {
                return ((string)(this["BingUrl"]));
            }
            set {
                this["BingUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(?<=(g_img={.*?url:\'))http://.*?\\.jpg(?=(\'.*}))|(?<=(<div\\sid=\\\"bgDiv\\\".*?style=\'" +
            ".*?background-image:\\s*url\\(\\\"))(http://.*?\\.jpg)(?=(\\\"\\);.*?\'.*?>))")]
        public string ImageUrlPatternFromBingUrl {
            get {
                return ((string)(this["ImageUrlPatternFromBingUrl"]));
            }
            set {
                this["ImageUrlPatternFromBingUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(?<=/)\\w*(?=_.*?\\.jpg)")]
        public string ImageFileNamePatternFromImageUrl {
            get {
                return ((string)(this["ImageFileNamePatternFromImageUrl"]));
            }
            set {
                this["ImageFileNamePatternFromImageUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("必应")]
        public string BingImageFolderName {
            get {
                return ((string)(this["BingImageFolderName"]));
            }
            set {
                this["BingImageFolderName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RecentBingImageFileName {
            get {
                return ((string)(this["RecentBingImageFileName"]));
            }
            set {
                this["RecentBingImageFileName"] = value;
            }
        }
    }
}
